// ─────────────────────────────────────────────────────────────
// data.js — tout le contenu du folio. Édite ici, rien d'autre.
// Sources : LinkedIn public + archives jeremy.design (2024-2025).
// ─────────────────────────────────────────────────────────────
const DATA = {
  name: "Jeremy Jones",
  handle: "jeremyjonesdesign",
  title: "Product Maker",
  location: "Paris, France",
  email: "contact@jeremy.design",
  bio: [
    "Multidisciplinary product designer. 17+ years in the industry — started in 2008.",
    "From IC to Head of. SaaS, gaming, healthcare & fashion. USA & Europe.",
    "3 years designing Cycle (cycle.app), until its acquisition by Atlassian.",
    "Now: AI Innovation Product at a stealth legal-tech startup (Remote / NYC). Nights & weekends: I design AND build my own products.",
  ],
  quote: {
    text: "For every complex problem, there is an answer that is clear, simple and wrong.",
    author: "H.L. Mencken",
  },
  work: [
    {
      period: "now",
      company: "Stealth",
      role: "AI Innovation Product",
      note: "Stealth startup — legal industry. Remote / NYC.",
    },
    {
      period: "2025",
      company: "Contentsquare",
      role: "Innovation AI Product",
      note: "Digital experience analytics.",
      url: "https://contentsquare.com",
    },
    {
      period: "2022 — 2025",
      company: "Cycle",
      role: "Head of Product Design",
      note: "3 years building cycle.app — AI-powered product feedback. Acquired by Atlassian.",
      url: "https://www.atlassian.com",
    },
    {
      period: "2024",
      company: "Arcads.ai",
      role: "Senior Product Designer",
      note: "AI-generated video ads.",
      url: "https://www.arcads.ai",
    },
    {
      period: "2021",
      company: "Mozza",
      role: "Senior Product Designer",
      note: "Product & engineering studio.",
      url: "https://www.mozza.io",
    },
    {
      period: "independent",
      company: "Async",
      role: "Head of Product Design",
      note: "Voice-first collaboration, with Ilan Abehassera.",
      url: "https://async.com",
    },
    {
      period: "independent",
      company: "Typology",
      role: "Product Designer",
      note: "Designed the Typology app — from ideation to execution.",
      url: "https://typology.com",
    },
    {
      period: "2008 — 2018",
      company: "Independent",
      role: "Visual Product Designer",
      note: "Facebook, Activision, Hermès, Chartboost, Voodoo, Spendesk, June, Etam, Edenred…",
    },
  ],
  education: "Institut Ingemedia — 2008-2010",
  clients: [
    "Arcads", "Facebook", "Activision", "Hermès", "Chartboost", "Voodoo", "Spendesk",
    "Typology", "June", "Async", "STid", "Brigad", "Mozza", "Hexa",
    "Etam", "Immosquare", "Edenred", "Tchek",
  ],
  projects: [
    {
      id: "openmat",
      name: "OpenMat",
      desc: "Training companion for grapplers. Find open mats, log your rolls.",
      stack: "Astro · iOS · Android",
      status: "live",
      url: "https://openmat.fr",
    },
    {
      id: "coachingsimple",
      name: "CoachingSimple",
      desc: "Full coaching platform — programs, nutrition, payments, AI program generation.",
      stack: "Next.js · tRPC · Supabase · Stripe",
      status: "live",
      url: "https://www.coachingsimple.fr",
    },
    {
      id: "summail",
      name: "Summail",
      desc: "Inbox triage — your unread, summarized into one morning digest.",
      stack: "Next.js · Claude API",
      status: "private",
    },
    {
      id: "tariff",
      name: "Tariff",
      desc: "Real-time customs & import-duty calculator for cross-border sellers.",
      stack: "Next.js · React 19",
      status: "private",
    },
    {
      id: "benchmark",
      name: "Benchmark",
      desc: "Head-to-head harness to score LLMs on your own prompts.",
      stack: "TypeScript · CLI",
      status: "private",
    },
    {
      id: "audioletter",
      name: "AudioLetter",
      desc: "Turns the newsletters you actually read into a daily audio digest.",
      stack: "Next.js · TTS",
      status: "private",
    },
    {
      id: "spellbook",
      name: "Spellbook",
      desc: "A versioned prompt library — your best prompts, one keystroke away.",
      stack: "Astro · MDX",
      status: "private",
    },
  ],
  more: "+ ~15 more experiments in ~/projects — ask me.",
  kudos: [
    {
      who: "Ilan Abehassera",
      org: "Async",
      avatar: "img/kudos/ilan.jpg",
      text: "I've worked with many UX/UI designers over the past 15 years for a few venture-backed startups, and Jeremy has consistently over delivered. He gets things fast, he has taste, and knows how to adapt to the product he's building. He's the best!",
    },
    {
      who: "Enzo Avigo",
      org: "June",
      avatar: "img/kudos/enzo.jpg",
      text: "Jeremy is a prodigious designer. He managed to deliver a really well rounded experience within a few weeks only 🔥",
    },
    {
      who: "Pierre Bascoul",
      org: "Typology",
      avatar: "img/kudos/pierre.jpg",
      text: "Jeremy has been instrumental in the development of our Typology application. Genuine expertise in UX and UI design, contributing at every stage from ideation to execution.",
    },
    {
      who: "Cédric Taravella",
      org: "Etam",
      avatar: "img/kudos/cedric.jpg",
      text: "Jeremy designed our progressive web app. He perfectly understood our needs and our ambition. Efficient, solution minded and passionate.",
    },
    {
      who: "Jean Davoust",
      org: "STid",
      avatar: "img/kudos/jean.jpg",
      text: "Very challenging schedule — Jeremy adapted perfectly to the time constraints and the team needs. He quickly grasps business issues and produces very efficiently.",
    },
  ],
  links: {
    github: "https://github.com/jeremyjonesdesign",
    linkedin: "https://www.linkedin.com/in/jeremy-jones-designer/",
    dribbble: "https://dribbble.com/jeijones",
  },
};
